DROP TABLE IF EXISTS ticket;
 
CREATE TABLE ticket (
  id INT PRIMARY KEY,
  bought BOOLEAN DEFAULT FALSE,
  picked BOOLEAN DEFAULT FALSE,
  user VARCHAR(250) DEFAULT NULL
);

INSERT INTO Ticket (id) VALUES (1);
INSERT INTO Ticket (id) VALUES (2);
INSERT INTO Ticket (id) VALUES (3);
INSERT INTO Ticket (id) VALUES (4);
INSERT INTO Ticket (id) VALUES (5);
INSERT INTO Ticket (id) VALUES (6);
INSERT INTO Ticket (id) VALUES (7);
INSERT INTO Ticket (id) VALUES (8);
INSERT INTO Ticket (id) VALUES (9);
INSERT INTO Ticket (id) VALUES (10);
INSERT INTO Ticket (id) VALUES (11);
INSERT INTO Ticket (id) VALUES (20);
INSERT INTO Ticket (id) VALUES (30);
INSERT INTO Ticket (id) VALUES (40);
INSERT INTO Ticket (id) VALUES (50);
INSERT INTO Ticket (id) VALUES (60);
INSERT INTO Ticket (id) VALUES (70);
INSERT INTO Ticket (id) VALUES (80);
INSERT INTO Ticket (id) VALUES (90);
INSERT INTO Ticket (id) VALUES (100);
INSERT INTO Ticket (id) VALUES (401);
INSERT INTO Ticket (id) VALUES (501);
INSERT INTO Ticket (id) VALUES (601);
INSERT INTO Ticket (id) VALUES (701);
INSERT INTO Ticket (id) VALUES (801);
INSERT INTO Ticket (id) VALUES (901);
INSERT INTO Ticket (id) VALUES (1001);


 
DROP TABLE IF EXISTS config;
 
CREATE TABLE config (
  id VARCHAR PRIMARY KEY,
  value VARCHAR NOT NULL
);